#!/bin/bash
#chkconfig: 2345 95 20
#description: Manage the RDM Infinity Multivalue Web Server
#processname: riWeb
#
#Written By: Brandon Robinson, RDM Infinity, LLC  01/10/10
#Linux service to start the web server automatically
#

#source function
. /etc/rc.d/init.d/functions

pidfile="/var/run/riWeb.pid"


start(){
   echo -n  $"Starting RDM Infinity Multivalue Web Server"
   /rdm/ringojs/bin/ringo /rdm/ringojs/apps/riWeb/main.js > /dev/null &
   RETVAL=$?
   PID=$!
   touch $pidfile
   echo $PID > "$pidfile"
   echo
   [ $RETVAL = 0 ] 
}

stop(){
  echo -n $"Stopping RDM Infinity Multivalue Web Server"
  killproc -p "$pidfile"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f "$pidfile"
}

case "$1" in 
  start)
  	start
 	;;
  stop)
	stop
	;;
  restart)
        stop
        start
        ;;
  status)
     echo -n $"Status of RDM Infinity Multivalue Web Server: "
     status -p "$pidfile"
     RETVAL=$?
     ;;
  *)
	echo $"Usage: riWeb {start|stop|status|restart}"
        exit 1

esac

exit $RETVAL
